services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.0
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'
  semantic_analyse_service:
    build:
      context: .
    container_name: semantic_analyse
    env_file:
      - ./.env
    depends_on:
      - weaviate
    ports:
      - 8000:8000
    restart: no
  # group_analyze_service:
  #   ...
  # frontend:
  #   ...
volumes:
  weaviate_data:
    driver: local
    driver_opts:
      type: none
      device: /home/grivvus/docker_volumes/weaviate
      o: bind
